### PR TITLE
:white_check_mark: add 4xx integration tests

### PR DESCRIPTION
**Pull request by ianardee**

### CODE REVIEW

**Review by sebastianMindee — CHANGES_REQUESTED** [review]
As long as we're at it, we might as well test `Parse_SyncOnly_AsyncMustFail`

**Review by thentgesMindee — COMMENTED** [review]
LGTM (can't really judge the code, but seeing the func names)
Just a note regarding what @sebastianMindee said about `Parse_SyncOnly_AsyncMustFail` I would suggest using a constructed APIs if you have some available, since we may enable asynchronous endpoints for our standards products in the future, that would make sure you don't need to change this.

**Comment by ianardee** [comment]
There was actually a problem with the way errors were handled for predict_async.

Good call @sebastianMindee :+1: 

I've updated the PR to properly handle errors by throwing an exception on 403 errors, and rebased the commits accordingly.

**Comment by ianardee** [comment]
> LGTM (can't really judge the code, but seeing the func names) Just a note regarding what @sebastianMindee said about `Parse_SyncOnly_AsyncMustFail` I would suggest using a constructed APIs if you have some available, since we may enable asynchronous endpoints for our standards products in the future, that would make sure you don't need to change this.

We don't support async calls on constructed products, we'll have to update this later.

**Comment by thentgesMindee** [comment]
@ianardee oh yes my bad, don't think it matters to support it, we will probably never enable asynchronous endpoints on constructed APIs

**Review by sebastianMindee — APPROVED** [review]

**Pull request merged**
